### ISSUE TITLE
concurrent.fututres

### ISSUE THREAD

**Issue by rcpilotp51** [kivy-garden/mapview#14]
I'm having an issue with concurrent.futures and mapview - I've installed futures but I and still getting this error:  
```
File "/.../libs/garden/garden.mapview/mapview/downloader.py", line 8, in <module>
     from concurrent.futures import ThreadPoolExecutor, TimeoutError, as_completed
 ImportError: No module named concurrent.futures
```

I've updated garden.mapview hoping it would help, but i'm having no luck - can anyone help?

**Comment by AndreMiras** [comment]
I think this is fixed now with the new garden structure.
Also Python 2 was dropped
