### ISSUE TITLE
Broken imports in examples

### ISSUE THREAD

**Issue by Equidamoid** [kivy-garden/mapview#18]
Probably something has changed in the way stuff is intalled in the past 2 years, but `import mapview` does not work anymore, `import kivy.garden.mapview` works.

Couple of examples:

* `simple_map.py`:
`from mapview import MapView, MapSource`
should be 
`from kivy.garden.mapview import MapView, MapSource`
* `map_browser.py`:
`#:import MapSource mapview.MapSource`
should be 
`#:import MapSource kivy.garden.mapview.MapSource`

**Comment by AndreMiras** [comment]
This should be fixed as we migrated to the new garden structure.
The new way of importing is now `from kivy_garden.mapview import MapView`. As of today I believe README.md and examples/ folder are up to date.
In the future we may also include automated testing to the example so we shouldn't see any regression of this type anymore
