### ISSUE TITLE
WMTS support

### ISSUE THREAD

**Issue by scls19fr** [kivy-garden/mapview#31]
Hello,

GPXSee is a nice software to display GPS log.
It have support for several kind of map server such a [WMTS](https://en.wikipedia.org/wiki/Web_Map_Tile_Service) and come with a lot of map server links such as

```
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.4" type="WMTS">
	<name>Cartes IGN</name>
	<url>https://wxs.ign.fr/pratique/geoportail/wmts</url>
	<copyright>Institut national de l’information géographique et forestière</copyright>
	<format>image/jpeg</format>
	<layer>GEOGRAPHICALGRIDSYSTEMS.MAPS</layer>
	<style>normal</style>
	<set>PM</set>
</map>
```

or

```
<?xml version="1.0" encoding="UTF-8"?>
<map xmlns="http://www.gpxsee.org/map/1.4" type="WMTS">
	<name>Photographies aériennes</name>
	<url>https://wxs.ign.fr/pratique/geoportail/wmts</url>
	<copyright>Institut national de l’information géographique et forestière</copyright>
	<format>image/jpeg</format>
	<layer>ORTHOIMAGERY.ORTHOPHOTOS</layer>
	<style>normal</style>
	<set>PM</set>
</map>
```

I was looking for a similar library in Python (as it's simpler than C++)

Unfortunately mapview doesn't seem to support this kind of map source.

Any chance to have this implemented?

Kind regards

**Comment by tshirtman** [comment]
I wouldn't expect it to be implemented by us, but we would probably be open to accepting contributions in that direction.
