### ISSUE TITLE
GeoJSON plotting not working

### ISSUE THREAD

**Issue by danieljuschus** [kivy-garden/mapview#52]
**Describe the bug**
The GeoJSON geometry plotting isn't working. There are no error messages, but the geometry just isn't shown.

**To Reproduce**
Running the [example](https://github.com/kivy-garden/mapview/blob/develop/examples/simple_geojson.py) produces the output shown in the first screenshot. No geometry is being plotted. I've also tried to put together a MWE for this:

```from kivy_garden.mapview import MapView
from kivy_garden.mapview.geojson import GeoJsonMapLayer
from kivy.app import App


class MapViewApp(App):
    def build(self):
        mapp = MapView(zoom=15, lat=50.6394, lon=3.057)
        m1 = GeoJsonMapLayer(source="lille.geojson")
        mapp.add_layer(m1)
        return mapp


MapViewApp().run()
```

with the following geojson input:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
          "stroke": "#000000",
          "stroke-width": 2,
          "color": "#000000"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            3.0445861816406246,
            50.640942655167514
          ],
          [
            3.062760829925537,
            50.64026225088228
          ]
        ]
      }
    }
  ]
}
```

It doesn't work either. Output is shown in the second screenshot below.

**Expected behavior**
GeoJSON line strings and polygons should be plotted on the map.

**Logs/output**
![image](https://user-images.githubusercontent.com/26310238/147912553-81920a89-f28d-49bb-abc2-b1e613929461.png)
![image](https://user-images.githubusercontent.com/26310238/147912632-42da5bf7-63f2-4ec5-b82d-026751ffb0ae.png)

**Platform (please complete the following information):**
 - OS: Linux
 - Python version: 3.9
 - release or git branch/commit: develop branch

**Comment by harrison-denton** [comment]
Hi Daniel,

Have you given [this](https://github.com/kivy-garden/mapview/pull/50) fix a try?

**Comment by danieljuschus** [comment]
Yes, now it's working!

![image](https://user-images.githubusercontent.com/26310238/150804282-26d84217-cb9c-44f3-b974-015f00a5a643.png)
